### ISSUE TITLE
uncaught type error

### ISSUE THREAD

**Issue by qxxst** [sbox-sandcastle/qxxst-keygen#1]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at getSong (index.js:229:39)
    at index.js:258:50
    at step (index.js:33:23)
    at Object.next (index.js:14:53)
    at index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (index.js:4:12)
    at playSong (index.js:254:16)
    at Object.<anonymous> (index.js:279:46)
    at step (index.js:33:23)
```
Not too sure what's going on with this but I'm going to fix it.

**Comment by qxxst** [comment]
Fixed
